#!/bin/bash

checkResult () {
  if [ -n "$(diff actual expected)" ] ; then
    echo "FAILED test $1"
    run=""
  fi
}

run="success"
./a.out . . 1 <input >actual
cut -d. --output-delimiter=. -f1 input >expected
checkResult 1

./a.out , . 1 <input >actual
cut -d, --output-delimiter=. -f1 input >expected
checkResult 2

./a.out . . 2 <input >actual
cut -d. --output-delimiter=. -f2 input >expected
checkResult 3

./a.out , . 2 <input >actual
cut -d, --output-delimiter=. -f2 input >expected
checkResult 4

./a.out . . 3 <input >actual
cut -d. --output-delimiter=. -f3 input >expected
checkResult 5

./a.out , . 3 <input >actual
cut -d, --output-delimiter=. -f3 input >expected
checkResult 6

./a.out . . 4 <input >actual
cut -d. --output-delimiter=. -f4 input >expected
checkResult 7

./a.out , . 4 <input >actual
cut -d, --output-delimiter=. -f4 input >expected
checkResult 8

./a.out . . 5 <input >actual
cut -d. --output-delimiter=. -f5 input >expected
checkResult 9

./a.out , . 5 <input >actual
cut -d, --output-delimiter=. -f5 input >expected
checkResult 10

./a.out . . 10 <input >actual
cut -d. --output-delimiter=. -f10 input >expected
checkResult 11

./a.out , . 10 <input >actual
cut -d, --output-delimiter=. -f10 input >expected
checkResult 12

if [ "$run" = "success" ] ; then
  echo "all tests successful"
fi